stages:
  - build
  - test
  - containerize

cache:
  key: $CI_BUILD_REF
  paths:
    - node_modules
    - dist
    - package.json
    - package-lock.json

build:
  stage: build
  image: node:10
  script:
    - npm install
    - npm run build-ts

test:
  stage: test
  image: node:10
  script:
    - npm test

containerize:
  stage: containerize
  image: docker:stable
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build -t gitlab.appcraft.com.br:4567/mutt/mutt-fipe-updater:latest .
    - docker push gitlab.appcraft.com.br:4567/mutt/mutt-fipe-updater:latest
