stages:
  - build
  - containerize

cache:
  key: $CI_BUILD_REF
  paths:
    - dist
    - server.js
    - package.json

build:
  stage: build
  image: node:10
  script:
    - npm install
    - npm run build

containerize:
  stage: containerize
  image: docker:18
  script:
    - docker info
    #- docker build -t user/my-typescript-image:latest
    #- docker push user/my-typescript-image:latest
