stages:
  - build
  - test
  - containerize

cache:
  key: $CI_BUILD_REF
  paths:
    - node_modules
    - dist
    - package.json
    - package-lock.json

build:
  stage: build
  image: node:10
  script:
    - npm install
    - npm run build-ts

test:
  stage: test
  image: node:10
  script:
    - npm test

containerize:
  stage: containerize
  image: docker:18
  script:
    - docker info
    #- docker build -t user/my-typescript-image:latest
    #- docker push user/my-typescript-image:latest
