stages:
  - build
  - test
  - containerize

cache:
  key: $CI_BUILD_REF
  paths:
    - node_modules
    - dist
    - package.json
    - package-lock.json

build:
  stage: build
  image: node:10
  script:
    - npm install
    - npm run build-ts

test:
  stage: test
  image: node:10
  script:
    - npm test

containerize:
  stage: containerize
  image: docker:stable
  script:
    - echo $CI_REGISTRY_USER
    - echo $CI_REGISTRY
    - docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t mutt/mutt-fipe-updated:latest .
    - docker push mutt/mutt-fipe-updated:latest
